### ISSUE TITLE
A team?

### ISSUE THREAD

**Issue by qingyuanzhao** [qingyuanzhao/2019-nCov-Data#1]
Please register your interest by replying to this thread. Sharing your ideas would be most welcomed.

**Comment by dsmall19** [comment]
I am interested in contributing -- Dylan Small

**Comment by zhouzilu** [comment]
I am interested in contributing too! - BTW, your "Issues" link in readme is broken...

**Comment by nianqiaoju** [comment]
I am interested in contributing. Phyllis Ju (nju@g.harvard.edu)

**Comment by qingyuanzhao** [comment]
Thank you everyone. Please take a look at #3 #4 #5 .

**Comment by qingyuanzhao** [comment]
> I am interested in contributing too! - BTW, your "Issues" link in readme is broken...

It works for me. Can you check again?

**Comment by anonymous-submission-tech** [comment]
I am interested in contributing. Yunjin Choi (ycstat@uos.ac.kr)

**Comment by Elsa-Yang98** [comment]
I am interested in contributing, the 'Issues' link doesn't work for me either. I can check some rows in the google spreadsheet to confirm them first.
Also I am wondering is there another spreadsheet for all the Chinese cases? And if there is anything else that can be done regarding #3 given that multiple imputation has already been done.

**Comment by Elsa-Yang98** [comment]
Also is there a column in the spreadsheet that can show if that row has been verified or not? I am assuming that the confirmed column is the indicator for when the patient has been confirmed of the virus.

**Comment by qingyuanzhao** [comment]
> I am interested in contributing. Yunjin Choi ([ycstat@uos.ac.kr](mailto:ycstat@uos.ac.kr))

Welcome. Issue #7 is relevant.

**Comment by qingyuanzhao** [comment]
Welcome
> I am interested in contributing, the 'Issues' link doesn't work for me either. I can check some rows in the google spreadsheet to confirm them first.

Should be fixed now.

> Also I am wondering is there another spreadsheet for all the Chinese cases? And if there is anything else that can be done regarding #3 given that multiple imputation has already been done.

Thanks. Created #8

**Comment by qingyuanzhao** [comment]
> Also is there a column in the spreadsheet that can show if that row has been verified or not? I am assuming that the confirmed column is the indicator for when the patient has been confirmed of the virus.

Thanks. Created a new column called "Verified" in the Spreadsheet.
In the future please open a new issue to make suggestions.
