### ISSUE TITLE
Cases in China

### ISSUE THREAD

**Issue by qingyuanzhao** [qingyuanzhao/2019-nCov-Data#8]
Suggestions by Cindy Chen in the Spreadsheet:

我发现北京卫健委每天都会以图标格式公布确诊患者的信息， 如果想做些关于效率的国别分析，这些数据都很clean的
http://wjw.beijing.gov.cn/xwzx_20031/wnxw/202002/t20200201_1622225.html
http://wjw.beijing.gov.cn/xwzx_20031/xwfb/202001/t20200131_1622025.html

上海卫建委也每天提供图表，只是关注的点不太一样
http://wsjkw.sh.gov.cn/xwfb/20200202/f5b6ce31678e43dca76c09d93ec4142b.html

合肥的报道也做的非常好，和你用的列都是一样的，我想这组数据可以用于做对照表http://www.bjnews.com.cn/news/2020/01/27/680324.html

If someone volunteers to add the data from Hefei, I can give you permission to edit the Spreadsheet.

**Comment by Elsa-Yang98** [comment]
There's an R package called "nCov2019" that records cases of each Province.

**Comment by qingyuanzhao** [comment]
> There's an R package called "nCov2019" that records cases of each Province.

Please provide a link in the future. Is [this](https://mp.weixin.qq.com/s/_0D8ENb-4lGm4UV16Ok28A) what you found? It is good to know. What we are doing (building a profile for each case) should be much more useful to understand the early epidemics.

@Else-Yang98 Do you want to work on recording .the data from Hefei?

**Comment by Elsa-Yang98** [comment]
@qingyuanzhao Yes that is what I found. 

I can record the data from Hefei using the link above that records the 13 cases in Hefei up to midnight, Jan.26th.
http://www.bjnews.com.cn/news/2020/01/27/680324.html

**Comment by qingyuanzhao** [comment]
@Elsa-Yang98 
Can you give me your email? Also I will put you as an appointee to this issue (doesn't mean you need to do more beyond the 13 Hefei cases).

**Comment by Elsa-Yang98** [comment]
I just found these three links recording up to midnight Jan.30th of the 50 cases in Hefei. I haven't completed the gap between Case 13 and Case 39--that's between Jan.26th and Jan.29th.
http://www.cnr.cn/ah/news/20200130/t20200130_524953535.shtml
https://m.chinanews.com/wap/detail/zw/sh/2020/01-30/9073457.shtml
http://society.people.com.cn/n1/2020/0131/c1008-31565828.html

Sure, my email is yachong@wharton.upenn.edu

**Comment by qingyuanzhao** [comment]
@Elsa-Yang98 I'm sending you an invitation to edit the Spreadsheet. Please record these cases using the "In China" sheet.

**Comment by Elsa-Yang98** [comment]
@qingyuanzhao  I finished the 13 cases in Hefei, please see if it's alright. I think the notes part should be written in English.... I will try to record all the 50 cases in Hefei

**Comment by qingyuanzhao** [comment]
Looks perfect. I'll verify once I can get to it.

**Comment by Elsa-Yang98** [comment]
I finished all the 75 cases that are confirmed of the disease up to Feb.2nd
This Wechat official account updates info daily 合肥交通广播
https://mp.weixin.qq.com/s/uhsgv_QO8DiXPjCkanMsfg

**Comment by Elsa-Yang98** [comment]
南京‘健康南京’这个公众号统计的也很详细，每天更新
https://mp.weixin.qq.com/s/29lyOHW8lUhWrVZ-zpMxTg

**Comment by qingyuanzhao** [comment]
Thanks, this data is very high-quality. Could you try to replicate the analysis here for the Hefei data? It'd be great to compare the estimates across different sources.

https://htmlpreview.github.io/?https://github.com/qingyuanzhao/2019-nCov-Data/blob/master/Feb3.html

Let me know if you need any help. The easiest way is to create a "fork" of this GitHub so you can work and update locally.

**Comment by qingyuanzhao** [comment]
Nanjing (I could only find detailed information from 29-Jan).

28-Jan: https://mp.weixin.qq.com/s/WaeUpQBuiJi_jPFhVFziQQ

29-Jan: https://mp.weixin.qq.com/s/q6oSShtpETmjdjMt06nlUw

30-Jan: https://mp.weixin.qq.com/s/BB_OX-wNCXz8GU0ZZYbjTA

31-Jan:
https://mp.weixin.qq.com/s/xjUZEj-T1iE2V6rc5BX-iQ

1-Feb: https://mp.weixin.qq.com/s/mDlDpN9hgnKRtXGGh2-W7w

2-Feb:
https://mp.weixin.qq.com/s/29lyOHW8lUhWrVZ-zpMxTg

3-Feb:
https://mp.weixin.qq.com/s/k4JsCyIwEbGjO82v4f5PAA

4-Feb:
https://mp.weixin.qq.com/s/USJ6P8Yfa7CuaNdGzvp_PQ

5-Feb: https://mp.weixin.qq.com/s/RIRb_rg4oaCJjAMCrk4HuQ

**Comment by qingyuanzhao** [comment]
安徽阜阳

up to 27-Jan:
https://www.hotbak.net/key/%E9%98%9C%E9%98%B323%E4%BE%8B%E7%A1%AE%E8%AF%8A%E7%97%85%E4%BE%8B%E4%BF%A1%E6%81%AF%E5%B1%85%E4%BD%8F%E5%9C%B0%E5%85%A8%E5%85%AC%E5%B8%83%E9%98%9C%E5%8D%97%E5%8E%BF.html

28-Jan:
https://feng.ifeng.com/c/7teaNNMVwbG

29-Jan:
http://www.ahbbs.cc/wap/37141-1.html

30-Jan:
https://feng.ifeng.com/c/7thljdXtGyp

31-Jan:
https://www.fynews.net/article-188245-1.html

1-Feb: 
https://www.fynews.net/article-188282-1.html

2-Feb:
http://ah.ifeng.com/a/20200203/8167754_0.shtml

3-Feb:
https://feng.ifeng.com/c/7toRODUgy80

4-Feb:
http://www.yxxsyxx.com/article-188422-1.html

5-Feb:
https://www.fynews.net/article-188480-1.html

6-Feb
http://www.ahwang.cn/newsflash/20200207/1978488.html

**Comment by qingyuanzhao** [comment]
河南信阳：

Up till 31-Jan:
http://www.scxww.cn/xww/xwsd/8683.shtml contains almost(?) all Henan cases up till 31-Jan.

30-Jan:
https://dahebao.cn/news/1488767?cid=1488767

31-Jan:
http://www.scxww.cn/xww/xwsd/8575.shtml

1-Feb:
http://www.scxww.cn/xww/xwsd/8658.shtml

2-Feb:
https://m.thepaper.cn/newsDetail_forward_5776587 

3-Feb:
https://4g.dahe.cn/news/20200204587310

4-Feb:
http://newwap.baoxiaofeng.com/news/73278

5-Feb:
https://www.twoeggz.com/info/216448.html

**Comment by nianqiaoju** [comment]
Anhui-Anqing:
You can find all the information here http://wjw.anqing.gov.cn/13971952.html
10-Feb: http://wjw.anqing.gov.cn/13971952/98351812.html
9-Feb: http://wjw.anqing.gov.cn/13971952/98211011.html
8-Feb: http://wjw.anqing.gov.cn/13971952/98087944.html

**Comment by nianqiaoju** [comment]
Anhui-Bengbu:
You can find all the information here: http://wjw.bengbu.gov.cn/
9-Feb: http://www.bbnews.cn/p/7471.html?spm=zm1143-001.0.0.1.bfnO3w
8-Feb: http://www.bbnews.cn/p/7450.html?spm=zm1143-001.0.0.1.QDW9PD
5-Feb: http://www.bbnews.cn/p/7413.html?spm=zm1143-001.0.0.1.vnxSjV

**Comment by qingyuanzhao** [comment]
Tianjin

http://tj.bendibao.com/news/2020130/86602.shtm (being updated)
